version: '3'
services:
  tool_portainer:
    container_name: 'godocker_portainer'
    image: portainer/portainer
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data portainer/portainer
  app:  
    container_name: app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - database
  web:
    container_name: web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 80:80
    depends_on:
      - app
  database:
    container_name: database
    image: postgres:10.3
    restart: always
    volumes:
      - pgdata:/var/lib/postgres
    environment:
        - POSTGRES_DB=godocker
        - POSTGRES_USER=nora
        - POSTGRES_PASSWORD=secret
    ports:
        - 54320:5432
volumes:
  pgdata: